server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.245.131
aliyun:
  sms:
    accessKeyId: LTAItfm18ptTZqN8
    accessKeySecret: uZFrlmYfA5wpn3wNOw76BMl0nAxchE
    sign_name: 超凡视幻
    template_code: SMS_160855463