server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      database: spitdb
      host: 192.168.245.131
  redis:
    host: 192.168.245.131
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6869/eureka
  instance:
    prefer-ip-address: true
jwt:
  config:
    key: jesus