server: 
   port: 9003
spring:
  application:
    name: tensquare-question #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.245.131:3306/tensquare_qa?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: mysql
    show-sql: true
jwt:
  config:
    key: jesus
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6869/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
